### ISSUE TITLE
Should have few more security measures

### ISSUE THREAD

**Issue by echoscriptor** [himanshurajora/ShareMyText#13]
For now anyone can write on any room and anyone can visit any room. This causes the following problems.
- Anyone can overwrite my data
- I can read someone's precious data if they didn't encrypt

Suggestions: 
- Block writing on a room for a specific time
- Make encrypting data compulsory. If someone didn't provide encryption key then give a random encryption key.

**Comment by himanshurajora** [comment]
Thanks @spark117code, This feedback is really meaningful.

**Comment by harsh-100** [comment]
Hey @spark117code ,not  much security is needed for this type of application as the beauty of this web app is easy to share with just few clicks , but if i need security and extra things here then why would as a user i will be using it , why not i will prefer using any other teams app 🤔
- as blocking for a specific time , What if 😅 i forget to share something in one shot and gave a time for 2 hrs then should i wait for two hours to share again in that room or should i create a new room 😒
- If you make the encrption compulsory , please provide that to the user 
###  suggestion 
-  why don't u completely remove the encrption part from the users end , do it by a random key make it easy for a user just to share the data in a room and give him that encryption key after sharing he can use to decrypt that 
- Giving a room name is also a time consuming for me and i can't think in one shot , so can you generate some fantasy room names (just like docker do in case of containers name 😜)  if user like it go with it else he can edit it also 

Thanks 😉

**Comment by himanshurajora** [comment]
Thanks @harsh-100, your feedback will surely make impact.

**Comment by himanshurajora** [comment]
We decided not to have any securities
